/*
 *    Copyright 2026 Ethan O'Connor
 *
 *    This file is part of OpenOrienteering.
 *
 *    OpenOrienteering is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OpenOrienteering is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OpenOrienteering.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef OPENORIENTEERING_ONLINE_IMAGERY_TEMPLATE_BUILDER_H
#define OPENORIENTEERING_ONLINE_IMAGERY_TEMPLATE_BUILDER_H

#include <QCoreApplication>
#include <QPointF>
#include <QRectF>
#include <QString>

#include "gdal/online_imagery_source.h"

namespace OpenOrienteering {

class Georeferencing;


/**
 * Detects, normalizes, and generates GDAL XML files for online imagery sources.
 *
 * This module:
 * 1. Classifies a pasted URL into a known source type
 * 2. Computes a tile-grid-aligned crop from a map object extent
 * 3. Generates a local GDAL WMS/TMS XML file suitable for GdalTemplate
 *
 * Phase 1 supports XYZ (top-origin EPSG:3857) and ArcGIS cached MapServer.
 */
class OnlineImageryTemplateBuilder
{
	Q_DECLARE_TR_FUNCTIONS(OpenOrienteering::OnlineImageryTemplateBuilder)

public:
	/**
	 * Result of URL classification.
	 */
	struct ClassifyResult
	{
		OnlineImagerySource source;
		QString error;   ///< Non-empty if the URL was rejected.
	};

	/**
	 * Result of XML generation.
	 */
	struct GenerateResult
	{
		QString xml_path;     ///< Path to the generated GDAL XML file.
		double area_km2 = 0;  ///< Cropped area in square kilometers.
		QString error;        ///< Non-empty on failure.
	};

	/**
	 * Classify a user-pasted URL. Synchronous, no network access.
	 *
	 * For XYZ sources, this fully populates the OnlineImagerySource.
	 * For ArcGIS sources, only kind + normalized_url are set; metadata
	 * must be fetched separately via the dialog's async path.
	 */
	static ClassifyResult classifyUrl(const QString& input);

	/**
	 * Generate a cropped GDAL XML file for the given source and map extent.
	 *
	 * @param source      Fully populated source description.
	 * @param map_extent  Object extent in map coordinates (from Map::calculateExtent).
	 * @param georef      Map's georeferencing (must be Geospatial).
	 * @param map_path    Path to the map file (XML written as sibling).
	 * @return            Result with XML path and area, or error.
	 */
	static GenerateResult generateXml(
		const OnlineImagerySource& source,
		const QRectF& map_extent,
		const Georeferencing& georef,
		const QString& map_path);

	/**
	 * Check whether a template file was generated by this builder.
	 * Looks for the marker comment in the file's first few lines.
	 */
	static bool isGeneratedOnlineTemplate(const QString& file_path);

	/**
	 * Compute a stable output filename for a generated XML file.
	 */
	static QString outputFileName(const QString& map_path, const OnlineImagerySource& source);

	/// Area warning threshold in square kilometers.
	static constexpr double area_warning_threshold_km2 = 200.0;

private:
	/**
	 * Convert a lat/lon point to EPSG:3857 Web Mercator coordinates.
	 */
	static QPointF latLonToWebMercator(double lat_deg, double lon_deg);

	/**
	 * Compute the EPSG:3857 bounding box for a map extent,
	 * converting via the map's georeferencing.
	 */
	static QRectF mapExtentToWebMercator(
		const QRectF& map_extent,
		const Georeferencing& georef);

	/**
	 * Snap a Web Mercator bounding box to the TMS tile grid at
	 * the given level. Returns the tile index range and the
	 * snapped projected bounds.
	 */
	struct TileGridCrop
	{
		int tile_x_min = 0;
		int tile_y_min = 0;
		int tile_x_max = 0;
		int tile_y_max = 0;
		int tile_level = 0;
		// Projected bounds in EPSG:3857 (NOT QRectF — geographic Y is up).
		double west = 0;   ///< UpperLeftX (minimum easting)
		double north = 0;  ///< UpperLeftY (maximum northing)
		double east = 0;   ///< LowerRightX (maximum easting)
		double south = 0;  ///< LowerRightY (minimum northing)
		int pixel_width = 0;
		int pixel_height = 0;
	};

	static TileGridCrop snapToTileGrid(
		const QRectF& mercator_bbox,
		int max_tile_level,
		int tile_size);
};


}  // namespace OpenOrienteering

#endif // OPENORIENTEERING_ONLINE_IMAGERY_TEMPLATE_BUILDER_H
